google:
  enabled: true
  analytics_id: UA-66173253-1
  site_verification: A_-ni0kpjfoChPAbENtOg0BjtYUy-N-yTM9nXaBseAc

site:
  name: That camera guy
  title: That camera guy - Street photography London
  tagline: Street photography and stuff
  description: London street photography, shooting mostly film. Black and white, medium format and 35mm film, Zenza Bronica, Nikon
  domain: thacameraguy.co.uk
  full_domain: http://thatcameraguy.co.uk

images:
  server: http://s3-eu-west-1.amazonaws.com/thatcameraguy/
